// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organizations.proto

package com.jerolba.xbuffers.protocol;

public interface OrganizationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jerolba.xbuffers.protocol.Organization)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string category = 2;</code>
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 2;</code>
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>.com.jerolba.xbuffers.protocol.Organization.OrganizationType type = 3;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.jerolba.xbuffers.protocol.Organization.OrganizationType type = 3;</code>
   */
  com.jerolba.xbuffers.protocol.Organization.OrganizationType getType();

  /**
   * <code>string country = 4;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 4;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
   */
  java.util.List<com.jerolba.xbuffers.protocol.Organization.Attribute> 
      getAttributesList();
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
   */
  com.jerolba.xbuffers.protocol.Organization.Attribute getAttributes(int index);
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
   */
  int getAttributesCount();
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
   */
  java.util.List<? extends com.jerolba.xbuffers.protocol.Organization.AttributeOrBuilder> 
      getAttributesOrBuilderList();
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
   */
  com.jerolba.xbuffers.protocol.Organization.AttributeOrBuilder getAttributesOrBuilder(
      int index);
}
