// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organizations.proto

package com.jerolba.xbuffers.protocol;

/**
 * Protobuf type {@code com.jerolba.xbuffers.protocol.Organization}
 */
public  final class Organization extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.jerolba.xbuffers.protocol.Organization)
    OrganizationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Organization.newBuilder() to construct.
  private Organization(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Organization() {
    name_ = "";
    category_ = "";
    type_ = 0;
    country_ = "";
    attributes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Organization(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            category_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            country_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              attributes_ = new java.util.ArrayList<com.jerolba.xbuffers.protocol.Organization.Attribute>();
              mutable_bitField0_ |= 0x00000010;
            }
            attributes_.add(
                input.readMessage(com.jerolba.xbuffers.protocol.Organization.Attribute.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        attributes_ = java.util.Collections.unmodifiableList(attributes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organization_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organization_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jerolba.xbuffers.protocol.Organization.class, com.jerolba.xbuffers.protocol.Organization.Builder.class);
  }

  /**
   * Protobuf enum {@code com.jerolba.xbuffers.protocol.Organization.OrganizationType}
   */
  public enum OrganizationType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FOO = 0;</code>
     */
    FOO(0),
    /**
     * <code>BAR = 1;</code>
     */
    BAR(1),
    /**
     * <code>BAZ = 2;</code>
     */
    BAZ(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FOO = 0;</code>
     */
    public static final int FOO_VALUE = 0;
    /**
     * <code>BAR = 1;</code>
     */
    public static final int BAR_VALUE = 1;
    /**
     * <code>BAZ = 2;</code>
     */
    public static final int BAZ_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OrganizationType valueOf(int value) {
      return forNumber(value);
    }

    public static OrganizationType forNumber(int value) {
      switch (value) {
        case 0: return FOO;
        case 1: return BAR;
        case 2: return BAZ;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OrganizationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OrganizationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrganizationType>() {
            public OrganizationType findValueByNumber(int number) {
              return OrganizationType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jerolba.xbuffers.protocol.Organization.getDescriptor().getEnumTypes().get(0);
    }

    private static final OrganizationType[] VALUES = values();

    public static OrganizationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OrganizationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jerolba.xbuffers.protocol.Organization.OrganizationType)
  }

  public interface AttributeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jerolba.xbuffers.protocol.Organization.Attribute)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int32 quantity = 2;</code>
     */
    int getQuantity();

    /**
     * <code>int32 amount = 3;</code>
     */
    int getAmount();

    /**
     * <code>int32 size = 4;</code>
     */
    int getSize();

    /**
     * <code>double percent = 5;</code>
     */
    double getPercent();

    /**
     * <code>bool active = 6;</code>
     */
    boolean getActive();
  }
  /**
   * Protobuf type {@code com.jerolba.xbuffers.protocol.Organization.Attribute}
   */
  public  static final class Attribute extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jerolba.xbuffers.protocol.Organization.Attribute)
      AttributeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Attribute.newBuilder() to construct.
    private Attribute(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Attribute() {
      id_ = "";
      quantity_ = 0;
      amount_ = 0;
      size_ = 0;
      percent_ = 0D;
      active_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Attribute(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              quantity_ = input.readInt32();
              break;
            }
            case 24: {

              amount_ = input.readInt32();
              break;
            }
            case 32: {

              size_ = input.readInt32();
              break;
            }
            case 41: {

              percent_ = input.readDouble();
              break;
            }
            case 48: {

              active_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organization_Attribute_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organization_Attribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jerolba.xbuffers.protocol.Organization.Attribute.class, com.jerolba.xbuffers.protocol.Organization.Attribute.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 2;
    private int quantity_;
    /**
     * <code>int32 quantity = 2;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private int amount_;
    /**
     * <code>int32 amount = 3;</code>
     */
    public int getAmount() {
      return amount_;
    }

    public static final int SIZE_FIELD_NUMBER = 4;
    private int size_;
    /**
     * <code>int32 size = 4;</code>
     */
    public int getSize() {
      return size_;
    }

    public static final int PERCENT_FIELD_NUMBER = 5;
    private double percent_;
    /**
     * <code>double percent = 5;</code>
     */
    public double getPercent() {
      return percent_;
    }

    public static final int ACTIVE_FIELD_NUMBER = 6;
    private boolean active_;
    /**
     * <code>bool active = 6;</code>
     */
    public boolean getActive() {
      return active_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (quantity_ != 0) {
        output.writeInt32(2, quantity_);
      }
      if (amount_ != 0) {
        output.writeInt32(3, amount_);
      }
      if (size_ != 0) {
        output.writeInt32(4, size_);
      }
      if (percent_ != 0D) {
        output.writeDouble(5, percent_);
      }
      if (active_ != false) {
        output.writeBool(6, active_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, quantity_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, amount_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, size_);
      }
      if (percent_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, percent_);
      }
      if (active_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, active_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jerolba.xbuffers.protocol.Organization.Attribute)) {
        return super.equals(obj);
      }
      com.jerolba.xbuffers.protocol.Organization.Attribute other = (com.jerolba.xbuffers.protocol.Organization.Attribute) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getQuantity()
          == other.getQuantity());
      result = result && (getAmount()
          == other.getAmount());
      result = result && (getSize()
          == other.getSize());
      result = result && (
          java.lang.Double.doubleToLongBits(getPercent())
          == java.lang.Double.doubleToLongBits(
              other.getPercent()));
      result = result && (getActive()
          == other.getActive());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (37 * hash) + PERCENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPercent()));
      hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getActive());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jerolba.xbuffers.protocol.Organization.Attribute parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jerolba.xbuffers.protocol.Organization.Attribute prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jerolba.xbuffers.protocol.Organization.Attribute}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jerolba.xbuffers.protocol.Organization.Attribute)
        com.jerolba.xbuffers.protocol.Organization.AttributeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organization_Attribute_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organization_Attribute_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jerolba.xbuffers.protocol.Organization.Attribute.class, com.jerolba.xbuffers.protocol.Organization.Attribute.Builder.class);
      }

      // Construct using com.jerolba.xbuffers.protocol.Organization.Attribute.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        quantity_ = 0;

        amount_ = 0;

        size_ = 0;

        percent_ = 0D;

        active_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organization_Attribute_descriptor;
      }

      public com.jerolba.xbuffers.protocol.Organization.Attribute getDefaultInstanceForType() {
        return com.jerolba.xbuffers.protocol.Organization.Attribute.getDefaultInstance();
      }

      public com.jerolba.xbuffers.protocol.Organization.Attribute build() {
        com.jerolba.xbuffers.protocol.Organization.Attribute result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jerolba.xbuffers.protocol.Organization.Attribute buildPartial() {
        com.jerolba.xbuffers.protocol.Organization.Attribute result = new com.jerolba.xbuffers.protocol.Organization.Attribute(this);
        result.id_ = id_;
        result.quantity_ = quantity_;
        result.amount_ = amount_;
        result.size_ = size_;
        result.percent_ = percent_;
        result.active_ = active_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jerolba.xbuffers.protocol.Organization.Attribute) {
          return mergeFrom((com.jerolba.xbuffers.protocol.Organization.Attribute)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jerolba.xbuffers.protocol.Organization.Attribute other) {
        if (other == com.jerolba.xbuffers.protocol.Organization.Attribute.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (other.getPercent() != 0D) {
          setPercent(other.getPercent());
        }
        if (other.getActive() != false) {
          setActive(other.getActive());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jerolba.xbuffers.protocol.Organization.Attribute parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jerolba.xbuffers.protocol.Organization.Attribute) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 2;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 2;</code>
       */
      public Builder setQuantity(int value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 2;</code>
       */
      public Builder clearQuantity() {
        
        quantity_ = 0;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>int32 amount = 3;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>int32 amount = 3;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 amount = 3;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>int32 size = 4;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 size = 4;</code>
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 size = 4;</code>
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private double percent_ ;
      /**
       * <code>double percent = 5;</code>
       */
      public double getPercent() {
        return percent_;
      }
      /**
       * <code>double percent = 5;</code>
       */
      public Builder setPercent(double value) {
        
        percent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double percent = 5;</code>
       */
      public Builder clearPercent() {
        
        percent_ = 0D;
        onChanged();
        return this;
      }

      private boolean active_ ;
      /**
       * <code>bool active = 6;</code>
       */
      public boolean getActive() {
        return active_;
      }
      /**
       * <code>bool active = 6;</code>
       */
      public Builder setActive(boolean value) {
        
        active_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool active = 6;</code>
       */
      public Builder clearActive() {
        
        active_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jerolba.xbuffers.protocol.Organization.Attribute)
    }

    // @@protoc_insertion_point(class_scope:com.jerolba.xbuffers.protocol.Organization.Attribute)
    private static final com.jerolba.xbuffers.protocol.Organization.Attribute DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jerolba.xbuffers.protocol.Organization.Attribute();
    }

    public static com.jerolba.xbuffers.protocol.Organization.Attribute getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Attribute>
        PARSER = new com.google.protobuf.AbstractParser<Attribute>() {
      public Attribute parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Attribute(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Attribute> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Attribute> getParserForType() {
      return PARSER;
    }

    public com.jerolba.xbuffers.protocol.Organization.Attribute getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 2;
  private volatile java.lang.Object category_;
  /**
   * <code>string category = 2;</code>
   */
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <code>string category = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <code>.com.jerolba.xbuffers.protocol.Organization.OrganizationType type = 3;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.com.jerolba.xbuffers.protocol.Organization.OrganizationType type = 3;</code>
   */
  public com.jerolba.xbuffers.protocol.Organization.OrganizationType getType() {
    com.jerolba.xbuffers.protocol.Organization.OrganizationType result = com.jerolba.xbuffers.protocol.Organization.OrganizationType.valueOf(type_);
    return result == null ? com.jerolba.xbuffers.protocol.Organization.OrganizationType.UNRECOGNIZED : result;
  }

  public static final int COUNTRY_FIELD_NUMBER = 4;
  private volatile java.lang.Object country_;
  /**
   * <code>string country = 4;</code>
   */
  public java.lang.String getCountry() {
    java.lang.Object ref = country_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      country_ = s;
      return s;
    }
  }
  /**
   * <code>string country = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCountryBytes() {
    java.lang.Object ref = country_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      country_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 5;
  private java.util.List<com.jerolba.xbuffers.protocol.Organization.Attribute> attributes_;
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
   */
  public java.util.List<com.jerolba.xbuffers.protocol.Organization.Attribute> getAttributesList() {
    return attributes_;
  }
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
   */
  public java.util.List<? extends com.jerolba.xbuffers.protocol.Organization.AttributeOrBuilder> 
      getAttributesOrBuilderList() {
    return attributes_;
  }
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
   */
  public int getAttributesCount() {
    return attributes_.size();
  }
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
   */
  public com.jerolba.xbuffers.protocol.Organization.Attribute getAttributes(int index) {
    return attributes_.get(index);
  }
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
   */
  public com.jerolba.xbuffers.protocol.Organization.AttributeOrBuilder getAttributesOrBuilder(
      int index) {
    return attributes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getCategoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, category_);
    }
    if (type_ != com.jerolba.xbuffers.protocol.Organization.OrganizationType.FOO.getNumber()) {
      output.writeEnum(3, type_);
    }
    if (!getCountryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, country_);
    }
    for (int i = 0; i < attributes_.size(); i++) {
      output.writeMessage(5, attributes_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getCategoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, category_);
    }
    if (type_ != com.jerolba.xbuffers.protocol.Organization.OrganizationType.FOO.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    if (!getCountryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, country_);
    }
    for (int i = 0; i < attributes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, attributes_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jerolba.xbuffers.protocol.Organization)) {
      return super.equals(obj);
    }
    com.jerolba.xbuffers.protocol.Organization other = (com.jerolba.xbuffers.protocol.Organization) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getCategory()
        .equals(other.getCategory());
    result = result && type_ == other.type_;
    result = result && getCountry()
        .equals(other.getCountry());
    result = result && getAttributesList()
        .equals(other.getAttributesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
    hash = (53 * hash) + getCountry().hashCode();
    if (getAttributesCount() > 0) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + getAttributesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jerolba.xbuffers.protocol.Organization parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jerolba.xbuffers.protocol.Organization parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jerolba.xbuffers.protocol.Organization prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.jerolba.xbuffers.protocol.Organization}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.jerolba.xbuffers.protocol.Organization)
      com.jerolba.xbuffers.protocol.OrganizationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organization_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organization_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jerolba.xbuffers.protocol.Organization.class, com.jerolba.xbuffers.protocol.Organization.Builder.class);
    }

    // Construct using com.jerolba.xbuffers.protocol.Organization.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAttributesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      category_ = "";

      type_ = 0;

      country_ = "";

      if (attributesBuilder_ == null) {
        attributes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        attributesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organization_descriptor;
    }

    public com.jerolba.xbuffers.protocol.Organization getDefaultInstanceForType() {
      return com.jerolba.xbuffers.protocol.Organization.getDefaultInstance();
    }

    public com.jerolba.xbuffers.protocol.Organization build() {
      com.jerolba.xbuffers.protocol.Organization result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jerolba.xbuffers.protocol.Organization buildPartial() {
      com.jerolba.xbuffers.protocol.Organization result = new com.jerolba.xbuffers.protocol.Organization(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.category_ = category_;
      result.type_ = type_;
      result.country_ = country_;
      if (attributesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.attributes_ = attributes_;
      } else {
        result.attributes_ = attributesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jerolba.xbuffers.protocol.Organization) {
        return mergeFrom((com.jerolba.xbuffers.protocol.Organization)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jerolba.xbuffers.protocol.Organization other) {
      if (other == com.jerolba.xbuffers.protocol.Organization.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getCountry().isEmpty()) {
        country_ = other.country_;
        onChanged();
      }
      if (attributesBuilder_ == null) {
        if (!other.attributes_.isEmpty()) {
          if (attributes_.isEmpty()) {
            attributes_ = other.attributes_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureAttributesIsMutable();
            attributes_.addAll(other.attributes_);
          }
          onChanged();
        }
      } else {
        if (!other.attributes_.isEmpty()) {
          if (attributesBuilder_.isEmpty()) {
            attributesBuilder_.dispose();
            attributesBuilder_ = null;
            attributes_ = other.attributes_;
            bitField0_ = (bitField0_ & ~0x00000010);
            attributesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttributesFieldBuilder() : null;
          } else {
            attributesBuilder_.addAllMessages(other.attributes_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jerolba.xbuffers.protocol.Organization parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jerolba.xbuffers.protocol.Organization) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <code>string category = 2;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string category = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string category = 2;</code>
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      category_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string category = 2;</code>
     */
    public Builder clearCategory() {
      
      category_ = getDefaultInstance().getCategory();
      onChanged();
      return this;
    }
    /**
     * <code>string category = 2;</code>
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      category_ = value;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.com.jerolba.xbuffers.protocol.Organization.OrganizationType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.jerolba.xbuffers.protocol.Organization.OrganizationType type = 3;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.jerolba.xbuffers.protocol.Organization.OrganizationType type = 3;</code>
     */
    public com.jerolba.xbuffers.protocol.Organization.OrganizationType getType() {
      com.jerolba.xbuffers.protocol.Organization.OrganizationType result = com.jerolba.xbuffers.protocol.Organization.OrganizationType.valueOf(type_);
      return result == null ? com.jerolba.xbuffers.protocol.Organization.OrganizationType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.jerolba.xbuffers.protocol.Organization.OrganizationType type = 3;</code>
     */
    public Builder setType(com.jerolba.xbuffers.protocol.Organization.OrganizationType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.jerolba.xbuffers.protocol.Organization.OrganizationType type = 3;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object country_ = "";
    /**
     * <code>string country = 4;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string country = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string country = 4;</code>
     */
    public Builder setCountry(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      country_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string country = 4;</code>
     */
    public Builder clearCountry() {
      
      country_ = getDefaultInstance().getCountry();
      onChanged();
      return this;
    }
    /**
     * <code>string country = 4;</code>
     */
    public Builder setCountryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      country_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.jerolba.xbuffers.protocol.Organization.Attribute> attributes_ =
      java.util.Collections.emptyList();
    private void ensureAttributesIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        attributes_ = new java.util.ArrayList<com.jerolba.xbuffers.protocol.Organization.Attribute>(attributes_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jerolba.xbuffers.protocol.Organization.Attribute, com.jerolba.xbuffers.protocol.Organization.Attribute.Builder, com.jerolba.xbuffers.protocol.Organization.AttributeOrBuilder> attributesBuilder_;

    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public java.util.List<com.jerolba.xbuffers.protocol.Organization.Attribute> getAttributesList() {
      if (attributesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attributes_);
      } else {
        return attributesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public int getAttributesCount() {
      if (attributesBuilder_ == null) {
        return attributes_.size();
      } else {
        return attributesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public com.jerolba.xbuffers.protocol.Organization.Attribute getAttributes(int index) {
      if (attributesBuilder_ == null) {
        return attributes_.get(index);
      } else {
        return attributesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public Builder setAttributes(
        int index, com.jerolba.xbuffers.protocol.Organization.Attribute value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.set(index, value);
        onChanged();
      } else {
        attributesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public Builder setAttributes(
        int index, com.jerolba.xbuffers.protocol.Organization.Attribute.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.set(index, builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public Builder addAttributes(com.jerolba.xbuffers.protocol.Organization.Attribute value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.add(value);
        onChanged();
      } else {
        attributesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public Builder addAttributes(
        int index, com.jerolba.xbuffers.protocol.Organization.Attribute value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.add(index, value);
        onChanged();
      } else {
        attributesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public Builder addAttributes(
        com.jerolba.xbuffers.protocol.Organization.Attribute.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.add(builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public Builder addAttributes(
        int index, com.jerolba.xbuffers.protocol.Organization.Attribute.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.add(index, builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public Builder addAllAttributes(
        java.lang.Iterable<? extends com.jerolba.xbuffers.protocol.Organization.Attribute> values) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attributes_);
        onChanged();
      } else {
        attributesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public Builder clearAttributes() {
      if (attributesBuilder_ == null) {
        attributes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        attributesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public Builder removeAttributes(int index) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.remove(index);
        onChanged();
      } else {
        attributesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public com.jerolba.xbuffers.protocol.Organization.Attribute.Builder getAttributesBuilder(
        int index) {
      return getAttributesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public com.jerolba.xbuffers.protocol.Organization.AttributeOrBuilder getAttributesOrBuilder(
        int index) {
      if (attributesBuilder_ == null) {
        return attributes_.get(index);  } else {
        return attributesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public java.util.List<? extends com.jerolba.xbuffers.protocol.Organization.AttributeOrBuilder> 
         getAttributesOrBuilderList() {
      if (attributesBuilder_ != null) {
        return attributesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attributes_);
      }
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public com.jerolba.xbuffers.protocol.Organization.Attribute.Builder addAttributesBuilder() {
      return getAttributesFieldBuilder().addBuilder(
          com.jerolba.xbuffers.protocol.Organization.Attribute.getDefaultInstance());
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public com.jerolba.xbuffers.protocol.Organization.Attribute.Builder addAttributesBuilder(
        int index) {
      return getAttributesFieldBuilder().addBuilder(
          index, com.jerolba.xbuffers.protocol.Organization.Attribute.getDefaultInstance());
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization.Attribute attributes = 5;</code>
     */
    public java.util.List<com.jerolba.xbuffers.protocol.Organization.Attribute.Builder> 
         getAttributesBuilderList() {
      return getAttributesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jerolba.xbuffers.protocol.Organization.Attribute, com.jerolba.xbuffers.protocol.Organization.Attribute.Builder, com.jerolba.xbuffers.protocol.Organization.AttributeOrBuilder> 
        getAttributesFieldBuilder() {
      if (attributesBuilder_ == null) {
        attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.jerolba.xbuffers.protocol.Organization.Attribute, com.jerolba.xbuffers.protocol.Organization.Attribute.Builder, com.jerolba.xbuffers.protocol.Organization.AttributeOrBuilder>(
                attributes_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        attributes_ = null;
      }
      return attributesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.jerolba.xbuffers.protocol.Organization)
  }

  // @@protoc_insertion_point(class_scope:com.jerolba.xbuffers.protocol.Organization)
  private static final com.jerolba.xbuffers.protocol.Organization DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jerolba.xbuffers.protocol.Organization();
  }

  public static com.jerolba.xbuffers.protocol.Organization getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Organization>
      PARSER = new com.google.protobuf.AbstractParser<Organization>() {
    public Organization parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Organization(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Organization> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Organization> getParserForType() {
    return PARSER;
  }

  public com.jerolba.xbuffers.protocol.Organization getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

