// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organizations.proto

package com.jerolba.xbuffers.protocol;

/**
 * Protobuf type {@code com.jerolba.xbuffers.protocol.Organizations}
 */
public  final class Organizations extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.jerolba.xbuffers.protocol.Organizations)
    OrganizationsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Organizations.newBuilder() to construct.
  private Organizations(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Organizations() {
    organizations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Organizations(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              organizations_ = new java.util.ArrayList<com.jerolba.xbuffers.protocol.Organization>();
              mutable_bitField0_ |= 0x00000001;
            }
            organizations_.add(
                input.readMessage(com.jerolba.xbuffers.protocol.Organization.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        organizations_ = java.util.Collections.unmodifiableList(organizations_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organizations_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organizations_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jerolba.xbuffers.protocol.Organizations.class, com.jerolba.xbuffers.protocol.Organizations.Builder.class);
  }

  public static final int ORGANIZATIONS_FIELD_NUMBER = 1;
  private java.util.List<com.jerolba.xbuffers.protocol.Organization> organizations_;
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
   */
  public java.util.List<com.jerolba.xbuffers.protocol.Organization> getOrganizationsList() {
    return organizations_;
  }
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
   */
  public java.util.List<? extends com.jerolba.xbuffers.protocol.OrganizationOrBuilder> 
      getOrganizationsOrBuilderList() {
    return organizations_;
  }
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
   */
  public int getOrganizationsCount() {
    return organizations_.size();
  }
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
   */
  public com.jerolba.xbuffers.protocol.Organization getOrganizations(int index) {
    return organizations_.get(index);
  }
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
   */
  public com.jerolba.xbuffers.protocol.OrganizationOrBuilder getOrganizationsOrBuilder(
      int index) {
    return organizations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < organizations_.size(); i++) {
      output.writeMessage(1, organizations_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < organizations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, organizations_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jerolba.xbuffers.protocol.Organizations)) {
      return super.equals(obj);
    }
    com.jerolba.xbuffers.protocol.Organizations other = (com.jerolba.xbuffers.protocol.Organizations) obj;

    boolean result = true;
    result = result && getOrganizationsList()
        .equals(other.getOrganizationsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOrganizationsCount() > 0) {
      hash = (37 * hash) + ORGANIZATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOrganizationsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jerolba.xbuffers.protocol.Organizations parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jerolba.xbuffers.protocol.Organizations parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jerolba.xbuffers.protocol.Organizations prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.jerolba.xbuffers.protocol.Organizations}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.jerolba.xbuffers.protocol.Organizations)
      com.jerolba.xbuffers.protocol.OrganizationsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organizations_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organizations_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jerolba.xbuffers.protocol.Organizations.class, com.jerolba.xbuffers.protocol.Organizations.Builder.class);
    }

    // Construct using com.jerolba.xbuffers.protocol.Organizations.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOrganizationsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (organizationsBuilder_ == null) {
        organizations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        organizationsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jerolba.xbuffers.protocol.OrganizationsCollection.internal_static_com_jerolba_xbuffers_protocol_Organizations_descriptor;
    }

    public com.jerolba.xbuffers.protocol.Organizations getDefaultInstanceForType() {
      return com.jerolba.xbuffers.protocol.Organizations.getDefaultInstance();
    }

    public com.jerolba.xbuffers.protocol.Organizations build() {
      com.jerolba.xbuffers.protocol.Organizations result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jerolba.xbuffers.protocol.Organizations buildPartial() {
      com.jerolba.xbuffers.protocol.Organizations result = new com.jerolba.xbuffers.protocol.Organizations(this);
      int from_bitField0_ = bitField0_;
      if (organizationsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          organizations_ = java.util.Collections.unmodifiableList(organizations_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.organizations_ = organizations_;
      } else {
        result.organizations_ = organizationsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jerolba.xbuffers.protocol.Organizations) {
        return mergeFrom((com.jerolba.xbuffers.protocol.Organizations)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jerolba.xbuffers.protocol.Organizations other) {
      if (other == com.jerolba.xbuffers.protocol.Organizations.getDefaultInstance()) return this;
      if (organizationsBuilder_ == null) {
        if (!other.organizations_.isEmpty()) {
          if (organizations_.isEmpty()) {
            organizations_ = other.organizations_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOrganizationsIsMutable();
            organizations_.addAll(other.organizations_);
          }
          onChanged();
        }
      } else {
        if (!other.organizations_.isEmpty()) {
          if (organizationsBuilder_.isEmpty()) {
            organizationsBuilder_.dispose();
            organizationsBuilder_ = null;
            organizations_ = other.organizations_;
            bitField0_ = (bitField0_ & ~0x00000001);
            organizationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrganizationsFieldBuilder() : null;
          } else {
            organizationsBuilder_.addAllMessages(other.organizations_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jerolba.xbuffers.protocol.Organizations parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jerolba.xbuffers.protocol.Organizations) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.jerolba.xbuffers.protocol.Organization> organizations_ =
      java.util.Collections.emptyList();
    private void ensureOrganizationsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        organizations_ = new java.util.ArrayList<com.jerolba.xbuffers.protocol.Organization>(organizations_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jerolba.xbuffers.protocol.Organization, com.jerolba.xbuffers.protocol.Organization.Builder, com.jerolba.xbuffers.protocol.OrganizationOrBuilder> organizationsBuilder_;

    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public java.util.List<com.jerolba.xbuffers.protocol.Organization> getOrganizationsList() {
      if (organizationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(organizations_);
      } else {
        return organizationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public int getOrganizationsCount() {
      if (organizationsBuilder_ == null) {
        return organizations_.size();
      } else {
        return organizationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public com.jerolba.xbuffers.protocol.Organization getOrganizations(int index) {
      if (organizationsBuilder_ == null) {
        return organizations_.get(index);
      } else {
        return organizationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public Builder setOrganizations(
        int index, com.jerolba.xbuffers.protocol.Organization value) {
      if (organizationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrganizationsIsMutable();
        organizations_.set(index, value);
        onChanged();
      } else {
        organizationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public Builder setOrganizations(
        int index, com.jerolba.xbuffers.protocol.Organization.Builder builderForValue) {
      if (organizationsBuilder_ == null) {
        ensureOrganizationsIsMutable();
        organizations_.set(index, builderForValue.build());
        onChanged();
      } else {
        organizationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public Builder addOrganizations(com.jerolba.xbuffers.protocol.Organization value) {
      if (organizationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrganizationsIsMutable();
        organizations_.add(value);
        onChanged();
      } else {
        organizationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public Builder addOrganizations(
        int index, com.jerolba.xbuffers.protocol.Organization value) {
      if (organizationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrganizationsIsMutable();
        organizations_.add(index, value);
        onChanged();
      } else {
        organizationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public Builder addOrganizations(
        com.jerolba.xbuffers.protocol.Organization.Builder builderForValue) {
      if (organizationsBuilder_ == null) {
        ensureOrganizationsIsMutable();
        organizations_.add(builderForValue.build());
        onChanged();
      } else {
        organizationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public Builder addOrganizations(
        int index, com.jerolba.xbuffers.protocol.Organization.Builder builderForValue) {
      if (organizationsBuilder_ == null) {
        ensureOrganizationsIsMutable();
        organizations_.add(index, builderForValue.build());
        onChanged();
      } else {
        organizationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public Builder addAllOrganizations(
        java.lang.Iterable<? extends com.jerolba.xbuffers.protocol.Organization> values) {
      if (organizationsBuilder_ == null) {
        ensureOrganizationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, organizations_);
        onChanged();
      } else {
        organizationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public Builder clearOrganizations() {
      if (organizationsBuilder_ == null) {
        organizations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        organizationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public Builder removeOrganizations(int index) {
      if (organizationsBuilder_ == null) {
        ensureOrganizationsIsMutable();
        organizations_.remove(index);
        onChanged();
      } else {
        organizationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public com.jerolba.xbuffers.protocol.Organization.Builder getOrganizationsBuilder(
        int index) {
      return getOrganizationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public com.jerolba.xbuffers.protocol.OrganizationOrBuilder getOrganizationsOrBuilder(
        int index) {
      if (organizationsBuilder_ == null) {
        return organizations_.get(index);  } else {
        return organizationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public java.util.List<? extends com.jerolba.xbuffers.protocol.OrganizationOrBuilder> 
         getOrganizationsOrBuilderList() {
      if (organizationsBuilder_ != null) {
        return organizationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(organizations_);
      }
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public com.jerolba.xbuffers.protocol.Organization.Builder addOrganizationsBuilder() {
      return getOrganizationsFieldBuilder().addBuilder(
          com.jerolba.xbuffers.protocol.Organization.getDefaultInstance());
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public com.jerolba.xbuffers.protocol.Organization.Builder addOrganizationsBuilder(
        int index) {
      return getOrganizationsFieldBuilder().addBuilder(
          index, com.jerolba.xbuffers.protocol.Organization.getDefaultInstance());
    }
    /**
     * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
     */
    public java.util.List<com.jerolba.xbuffers.protocol.Organization.Builder> 
         getOrganizationsBuilderList() {
      return getOrganizationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jerolba.xbuffers.protocol.Organization, com.jerolba.xbuffers.protocol.Organization.Builder, com.jerolba.xbuffers.protocol.OrganizationOrBuilder> 
        getOrganizationsFieldBuilder() {
      if (organizationsBuilder_ == null) {
        organizationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.jerolba.xbuffers.protocol.Organization, com.jerolba.xbuffers.protocol.Organization.Builder, com.jerolba.xbuffers.protocol.OrganizationOrBuilder>(
                organizations_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        organizations_ = null;
      }
      return organizationsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.jerolba.xbuffers.protocol.Organizations)
  }

  // @@protoc_insertion_point(class_scope:com.jerolba.xbuffers.protocol.Organizations)
  private static final com.jerolba.xbuffers.protocol.Organizations DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jerolba.xbuffers.protocol.Organizations();
  }

  public static com.jerolba.xbuffers.protocol.Organizations getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Organizations>
      PARSER = new com.google.protobuf.AbstractParser<Organizations>() {
    public Organizations parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Organizations(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Organizations> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Organizations> getParserForType() {
    return PARSER;
  }

  public com.jerolba.xbuffers.protocol.Organizations getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

