// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: organizations.proto

package com.jerolba.xbuffers.protocol;

public interface OrganizationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jerolba.xbuffers.protocol.Organizations)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
   */
  java.util.List<com.jerolba.xbuffers.protocol.Organization> 
      getOrganizationsList();
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
   */
  com.jerolba.xbuffers.protocol.Organization getOrganizations(int index);
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
   */
  int getOrganizationsCount();
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
   */
  java.util.List<? extends com.jerolba.xbuffers.protocol.OrganizationOrBuilder> 
      getOrganizationsOrBuilderList();
  /**
   * <code>repeated .com.jerolba.xbuffers.protocol.Organization organizations = 1;</code>
   */
  com.jerolba.xbuffers.protocol.OrganizationOrBuilder getOrganizationsOrBuilder(
      int index);
}
