/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.jerolba.xbuffers.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Organization extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6577215006293278905L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Organization\",\"namespace\":\"com.jerolba.xbuffers.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"category\",\"type\":\"string\"},{\"name\":\"organizationType\",\"type\":{\"type\":\"enum\",\"name\":\"OrganizationType\",\"symbols\":[\"FOO\",\"BAR\",\"BAZ\"]}},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"attributes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Attribute\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"amount\",\"type\":\"int\"},{\"name\":\"size\",\"type\":\"int\"},{\"name\":\"percent\",\"type\":\"double\"},{\"name\":\"active\",\"type\":\"boolean\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Organization> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Organization> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Organization> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Organization> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Organization> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Organization to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Organization from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Organization instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Organization fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private java.lang.CharSequence category;
  private com.jerolba.xbuffers.avro.OrganizationType organizationType;
  private java.lang.CharSequence country;
  private java.util.List<com.jerolba.xbuffers.avro.Attribute> attributes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Organization() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param category The new value for category
   * @param organizationType The new value for organizationType
   * @param country The new value for country
   * @param attributes The new value for attributes
   */
  public Organization(java.lang.CharSequence name, java.lang.CharSequence category, com.jerolba.xbuffers.avro.OrganizationType organizationType, java.lang.CharSequence country, java.util.List<com.jerolba.xbuffers.avro.Attribute> attributes) {
    this.name = name;
    this.category = category;
    this.organizationType = organizationType;
    this.country = country;
    this.attributes = attributes;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return category;
    case 2: return organizationType;
    case 3: return country;
    case 4: return attributes;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: category = (java.lang.CharSequence)value$; break;
    case 2: organizationType = (com.jerolba.xbuffers.avro.OrganizationType)value$; break;
    case 3: country = (java.lang.CharSequence)value$; break;
    case 4: attributes = (java.util.List<com.jerolba.xbuffers.avro.Attribute>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'category' field.
   * @return The value of the 'category' field.
   */
  public java.lang.CharSequence getCategory() {
    return category;
  }


  /**
   * Sets the value of the 'category' field.
   * @param value the value to set.
   */
  public void setCategory(java.lang.CharSequence value) {
    this.category = value;
  }

  /**
   * Gets the value of the 'organizationType' field.
   * @return The value of the 'organizationType' field.
   */
  public com.jerolba.xbuffers.avro.OrganizationType getOrganizationType() {
    return organizationType;
  }


  /**
   * Sets the value of the 'organizationType' field.
   * @param value the value to set.
   */
  public void setOrganizationType(com.jerolba.xbuffers.avro.OrganizationType value) {
    this.organizationType = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'attributes' field.
   * @return The value of the 'attributes' field.
   */
  public java.util.List<com.jerolba.xbuffers.avro.Attribute> getAttributes() {
    return attributes;
  }


  /**
   * Sets the value of the 'attributes' field.
   * @param value the value to set.
   */
  public void setAttributes(java.util.List<com.jerolba.xbuffers.avro.Attribute> value) {
    this.attributes = value;
  }

  /**
   * Creates a new Organization RecordBuilder.
   * @return A new Organization RecordBuilder
   */
  public static com.jerolba.xbuffers.avro.Organization.Builder newBuilder() {
    return new com.jerolba.xbuffers.avro.Organization.Builder();
  }

  /**
   * Creates a new Organization RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Organization RecordBuilder
   */
  public static com.jerolba.xbuffers.avro.Organization.Builder newBuilder(com.jerolba.xbuffers.avro.Organization.Builder other) {
    if (other == null) {
      return new com.jerolba.xbuffers.avro.Organization.Builder();
    } else {
      return new com.jerolba.xbuffers.avro.Organization.Builder(other);
    }
  }

  /**
   * Creates a new Organization RecordBuilder by copying an existing Organization instance.
   * @param other The existing instance to copy.
   * @return A new Organization RecordBuilder
   */
  public static com.jerolba.xbuffers.avro.Organization.Builder newBuilder(com.jerolba.xbuffers.avro.Organization other) {
    if (other == null) {
      return new com.jerolba.xbuffers.avro.Organization.Builder();
    } else {
      return new com.jerolba.xbuffers.avro.Organization.Builder(other);
    }
  }

  /**
   * RecordBuilder for Organization instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Organization>
    implements org.apache.avro.data.RecordBuilder<Organization> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence category;
    private com.jerolba.xbuffers.avro.OrganizationType organizationType;
    private java.lang.CharSequence country;
    private java.util.List<com.jerolba.xbuffers.avro.Attribute> attributes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.jerolba.xbuffers.avro.Organization.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.category)) {
        this.category = data().deepCopy(fields()[1].schema(), other.category);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.organizationType)) {
        this.organizationType = data().deepCopy(fields()[2].schema(), other.organizationType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.country)) {
        this.country = data().deepCopy(fields()[3].schema(), other.country);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.attributes)) {
        this.attributes = data().deepCopy(fields()[4].schema(), other.attributes);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Organization instance
     * @param other The existing instance to copy.
     */
    private Builder(com.jerolba.xbuffers.avro.Organization other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.category)) {
        this.category = data().deepCopy(fields()[1].schema(), other.category);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.organizationType)) {
        this.organizationType = data().deepCopy(fields()[2].schema(), other.organizationType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.country)) {
        this.country = data().deepCopy(fields()[3].schema(), other.country);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.attributes)) {
        this.attributes = data().deepCopy(fields()[4].schema(), other.attributes);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.jerolba.xbuffers.avro.Organization.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.jerolba.xbuffers.avro.Organization.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'category' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategory() {
      return category;
    }


    /**
      * Sets the value of the 'category' field.
      * @param value The value of 'category'.
      * @return This builder.
      */
    public com.jerolba.xbuffers.avro.Organization.Builder setCategory(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.category = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'category' field has been set.
      * @return True if the 'category' field has been set, false otherwise.
      */
    public boolean hasCategory() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'category' field.
      * @return This builder.
      */
    public com.jerolba.xbuffers.avro.Organization.Builder clearCategory() {
      category = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'organizationType' field.
      * @return The value.
      */
    public com.jerolba.xbuffers.avro.OrganizationType getOrganizationType() {
      return organizationType;
    }


    /**
      * Sets the value of the 'organizationType' field.
      * @param value The value of 'organizationType'.
      * @return This builder.
      */
    public com.jerolba.xbuffers.avro.Organization.Builder setOrganizationType(com.jerolba.xbuffers.avro.OrganizationType value) {
      validate(fields()[2], value);
      this.organizationType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'organizationType' field has been set.
      * @return True if the 'organizationType' field has been set, false otherwise.
      */
    public boolean hasOrganizationType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'organizationType' field.
      * @return This builder.
      */
    public com.jerolba.xbuffers.avro.Organization.Builder clearOrganizationType() {
      organizationType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public com.jerolba.xbuffers.avro.Organization.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.country = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public com.jerolba.xbuffers.avro.Organization.Builder clearCountry() {
      country = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'attributes' field.
      * @return The value.
      */
    public java.util.List<com.jerolba.xbuffers.avro.Attribute> getAttributes() {
      return attributes;
    }


    /**
      * Sets the value of the 'attributes' field.
      * @param value The value of 'attributes'.
      * @return This builder.
      */
    public com.jerolba.xbuffers.avro.Organization.Builder setAttributes(java.util.List<com.jerolba.xbuffers.avro.Attribute> value) {
      validate(fields()[4], value);
      this.attributes = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'attributes' field has been set.
      * @return True if the 'attributes' field has been set, false otherwise.
      */
    public boolean hasAttributes() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'attributes' field.
      * @return This builder.
      */
    public com.jerolba.xbuffers.avro.Organization.Builder clearAttributes() {
      attributes = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Organization build() {
      try {
        Organization record = new Organization();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.category = fieldSetFlags()[1] ? this.category : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.organizationType = fieldSetFlags()[2] ? this.organizationType : (com.jerolba.xbuffers.avro.OrganizationType) defaultValue(fields()[2]);
        record.country = fieldSetFlags()[3] ? this.country : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.attributes = fieldSetFlags()[4] ? this.attributes : (java.util.List<com.jerolba.xbuffers.avro.Attribute>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Organization>
    WRITER$ = (org.apache.avro.io.DatumWriter<Organization>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Organization>
    READER$ = (org.apache.avro.io.DatumReader<Organization>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.category);

    out.writeEnum(this.organizationType.ordinal());

    out.writeString(this.country);

    long size0 = this.attributes.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.jerolba.xbuffers.avro.Attribute e0: this.attributes) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.category = in.readString(this.category instanceof Utf8 ? (Utf8)this.category : null);

      this.organizationType = com.jerolba.xbuffers.avro.OrganizationType.values()[in.readEnum()];

      this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);

      long size0 = in.readArrayStart();
      java.util.List<com.jerolba.xbuffers.avro.Attribute> a0 = this.attributes;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.jerolba.xbuffers.avro.Attribute>((int)size0, SCHEMA$.getField("attributes").schema());
        this.attributes = a0;
      } else a0.clear();
      SpecificData.Array<com.jerolba.xbuffers.avro.Attribute> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.jerolba.xbuffers.avro.Attribute>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.jerolba.xbuffers.avro.Attribute e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.jerolba.xbuffers.avro.Attribute();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.category = in.readString(this.category instanceof Utf8 ? (Utf8)this.category : null);
          break;

        case 2:
          this.organizationType = com.jerolba.xbuffers.avro.OrganizationType.values()[in.readEnum()];
          break;

        case 3:
          this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<com.jerolba.xbuffers.avro.Attribute> a0 = this.attributes;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.jerolba.xbuffers.avro.Attribute>((int)size0, SCHEMA$.getField("attributes").schema());
            this.attributes = a0;
          } else a0.clear();
          SpecificData.Array<com.jerolba.xbuffers.avro.Attribute> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.jerolba.xbuffers.avro.Attribute>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.jerolba.xbuffers.avro.Attribute e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.jerolba.xbuffers.avro.Attribute();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










